const Usuario = require('./Usuario');
const Processador = require('./Processador');
const PlacaMae = require('./PlacaMae');
const Montagem = require('./Montagem');
const Ram = require('./Ram');
const Armazenamento = require('./Armazenamento');
const Vga = require('./Vga');
const Fonte = require('./Fonte')
module.exports = {Usuario, Processador, PlacaMae, Montagem, Ram, Armazenamento,Vga, Fonte}