const Usuario = require('./Usuario');
const Processador = require('./Processador');
const PlacaMae = require('./PlacaMae');
const Computador = require('./Computador');
const Ram = require('./Ram');
const Armazenamento = require('./Armazenamento');
const Vga = require('./Vga');
const Fonte = require('./Fonte');
const ComputadorArmazenamento = require('./ComputadorArmazenamento');
const ComputadorRam = require('./ComputadorRam');
module.exports = {Usuario, Processador, PlacaMae, Computador,ComputadorArmazenamento, ComputadorRam, Ram, Armazenamento,Vga, Fonte}