const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./app.js']
//const endpointsFiles = ['./docs/components.js']

//const component = require('./docs/components');
const doc = module.exports = {
  info: {
      version: "1.0.0",
      title: "My API",
      description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: "localhost:3000",
  basePath: "/",
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
      {
        "name": "Autenticacao",
        "description": "Metodos para trabalhar autenticacao e validacao de token"
      },
      {
          "name": "Usuario",
          "description": "Metodos para gerenciar Usuario"
      },
      {
        "name": "Processador",
        "description": "Metodos para gerenciar Processador"
      },
      {
        "name": "PlacaMae",
        "description": "Metodos para gerenciar Placa Mãe"
      },
      {
        "name": "Ram",
        "description": "Metodos para gerenciar Memória Ram"
      },
      {
        "name": "Armazenamento",
        "description": "Metodos para gerenciar Armazenamento"
      },
      {
        "name": "Vga",
        "description": "Metodos para gerenciar Vga"
      },
      {
        "name": "Fonte",
        "description": "Metodos para Fonte"
      },
      {
        "name": "Computador",
        "description": "Metodos para adicionar Hardwares a montagem do Computador"
      },
  ],
  securityDefinitions: {
      api_key: {
          type: "apiKey",
          name: "api_key",
          in: "header"
      },
      petstore_auth: {
          type: "oauth2",
          authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
          flow: "implicit",
          scopes: {
              read_pets: "read your pets",
              write_pets: "modify pets in your account"
          }
      }
  },
  models:{
      schemas:{
          nome: {
              type: "string", // data type
              description: "Nome e sobrenome do usuario separados por um '%'", // desc
              example: "?nome=josa%silva", // example of an id
          },
          id:{
              type: "Int", // data type
              description: "Nome e sobrenome do usuario separados por um '%'", // desc
              example: "1", // example of an id  
          },
          Usuario:{
              type: "object", // data type
              properties: {
                id: {
                  type: "string", // data-type
                  description: "Id do usuario", // desc
                  example: "1", // example of an id
                },
                username: {
                  type: "string", // data-type
                  description: "Username do usuario", // desc
                  example: "jose.silva", // example of a title
                },
                nome: {
                  type: "string", // data-type
                  description: "Nome do usuario", // desc
                  example: "Jose Silva", // example of a title
                },
                email: {
                  type: "string", // data-type
                  description: "Email do usuario", // desc
                  example: "Jose@gmail.com", // example of a title
                },
                senha: {
                  type: "string", // data-type
                  description: "Senha do usuario encriptada", // desc
                  example: "$2b$10$aJoUZq.P8ny12q8lY09KmuOxO6ZjuimHJEh6aNyvD7GvLGqGfP1M2", // example of a title
                }
              },
          },
          UsuarioPorNome:{
              Status:200,
              Usuario:{
                  type: "object", // data type
                  properties: {
                    id: {
                      type: "string", // data-type
                      description: "Id do usuario", // desc
                      example: "1", // example of an id
                    },
                    username: {
                      type: "string", // data-type
                      description: "Username do usuario", // desc
                      example: "jose.silva", // example of a title
                    },
                    nome: {
                      type: "string", // data-type
                      description: "Nome do usuario", // desc
                      example: "Jose Silva", // example of a title
                    },
                    email: {
                      type: "string", // data-type
                      description: "Email do usuario", // desc
                      example: "Jose@gmail.com", // example of a title
                    },
                    senha: {
                      type: "string", // data-type
                      description: "Senha do usuario encriptada", // desc
                      example: "$2b$10$aJoUZq.P8ny12q8lY09KmuOxO6ZjuimHJEh6aNyvD7GvLGqGfP1M2", // example of a title
                    },
                    completed: {
                      type: "boolean", // data type
                      description: "The status of the todo", // desc
                      example: false, // example of a completed value
                    },
                  },
              }  
          },
          Processador: {
            type: "object",
            properties: {
              id:{
                type: "integer",
                description: 'id do processador',
                example: 1
              },
              nome: {
                type: "string",
                description: "nome do processador",
                example: "INTEL CORE I7-10700KF"
              },
              marca: {
                type: "string",
                description: "marca do processador",
                example: "intel"
              },
              frequencia: {
                type: "number",
                description: "frequencia de trabalho do processador",
                example: 3.8
              },
              frequencia_max: {
                type: "number",
                description: "frequencia maxima de trabalho do processador",
                example: 5.1
              },
              socket: {
                type: "string",
                description: "socket do processador",
                example: "LGA1200"
              },
              tdp: {
                type: "integer",
                description: "Tdp do processador em wats",
                example: 95
              },
              consumo_max: {
                type: "number",
                description: "Consumo maximo do processador, calculado com uma taxa de 50% acima do tdp",
                example: 145
              },
            }

          },
          PlacaMae: {
            type: "object",
            properties: {
              id:{
                type: "integer",
                description: 'id da Placa Mae',
                example: 1
              },
              nome: {
                type: "string",
                description: "nome da placa mae",
                example: "Asus TUF Gaming Z490-Plus",
              },
              socket: {
                type: "string",
                description: "Tipo de socket de processador que é compatível com a placa mae",
                example: "LGA1200"
              },
              frequencia_max_ram: {
                type: "integer",
                description: "Frequencia maxima de memória ram suportada",
                example: 4800
              },
              max_ram: {
                type: "integer",
                description: "Quantidade máxima suportada de Ram em GB",
                example: 128
              },
              ddr: {
                type: "integer",
                description: "Representa a geração do tipo de memória, devendo ser ou 3, ou 4",
                example: 4
              },
              consumo: {
                type: "number",
                description: "Consumo da placa, sendo fixo o valor 35.",
                example: 35
              }
            }
          },
          Ram: {
            type: "object",
            properties: {
              id:{
                type: "integer",
                description: 'id da Memória Ram',
                example: 1
              },
              nome: {
                type: "string",
                description: "nome da Memória Ram",
                example: "TEAM GROUP T-FORCE RGB 8GB",
              },
              frequencia: {
                type: "integer",
                description: "Frequencia de trabalho do pente",
                example: 3600
              },
              capacidade: {
                type: "integer",
                description: "Quanto de Ram a memória posssui em GB",
                example: 8
              },
              ddr: {
                type: "integer",
                description: "Representa a geração do tipo de memória, devendo ser ou 3, ou 4",
                example: 4
              },
              consumo: {
                type: "number",
                description: "Quanto a memória consome de energia em watt. Por padrão, 3",
                example: "5"
              }
            }
          },
          Armazenamento: {
            type:"object",
            properties: {
              id:{
                type: "integer",
                description: 'id do Armazenamento',
                example: 1
              },
              nome: {
                type: "string",
                description: "nome do Armazenamento",
                example: "SSD Pichau Gaming",
              },
              capacidade: {
                type: "integer",
                description: "Capacidade que o HD/SSD possui de armazenmento",
                example: 280
              },
              consumo: {
                type: "integer",
                description: "Consumo de energia do armazenamento, sendo 12 por padrão.",
                example: 12
              }
            }
          },
          Vga: {
            type:"object",
            properties: {
              id:{
                type: "integer",
                description: 'id da Placa de Video',
                example: 1
              },
              nome: {
                type: "string",
                description: "nome da Placa de Video",
                example: "AMD Radeon RX 6800 XT",
              },
              capacidade: {
                type: "integer",
                description: "Capacidade que a Placa de Video processa em GB de Vram",
                example: 280
              },
              tdp: {
                type: "number",
                description: "Consumo de energia da Placa de Video",
                example: 300
              },
              consumo_max: {
                type: "number",
                description: "Consumo maximo de energia da placa de vídeo, calculado acrescendo 50% sobre o tdp",
                example: 450
              }
            }
          },
          Fonte: {
            type:"object",
            properties: {
              id:{
                type: "integer",
                description: 'id da Fonte',
                example: 1
              },
              nome: {
                type: "string",
                description: "nome da Fonte",
                example: "CoolerMaster V850 GOLD",
              },
              capacidade: {
                type: "integer",
                description: "Capacidade que o HD/SSD possui de armazenmento",
                example: 850
              }
            }
          },
          Computador: {

          }
      }
  },
  definitions: {
    ErroInterno:{
      status:500,
      message:"Erro interno no servidor!"
    },
    Autenticacao: {
      "username":"jose.silva",
      "senha":"123"
    },
    Autenticacao403: {
      "status": 403,
      "message": "Usuario ou senha incorreto!"
    },
    Autenticacao400CampoFaltando: {
      "status": 400,
      "message": "Ha campos faltando na requisicao: senha"
    },
    CadastroUsuario:{
        "username":"jose.silva",
        "nome":"Jose Silva",
        "email":"jose$@gmail.com",
        "senha":"123",
        "permissions":1
    },
    CadastroUsuarioResponse:{
      "id": 1,
      "username": "jose.silva",
      "nome": "Jose Silva",
      "email": "jose$@gmail.com",
      "senha": "$2b$10$suDSbebTCmuHl.YpTJ1Bj.IcKWyEBx2DzMD49NhbC.8330ZXOjOJe",
      "permissions": 1
    },
    Usuarios:{
      "status": 200,
      "usuarios": [
          {
              "id": 1,
              "nome": "teste 1",
              "username": "teste.1",
              "email": "teste$@gmail.com"
          },
          {
              "id": 2,
              "nome": "teste 2",
              "username": "teste.2",
              "email": "teste$@gmail.com"
          }
      ]
    },
    CadastroProcessador: {
      "nome":"INTEL CORE I7-10700KF",
      "marca":"Intel",
      "frequencia":3.8,
      "frequencia_max":5.1,
      "socket":"LGA1200",
      "tdp":95
    },
    ListarProcessador: 
      [
        {
            "id": 1,
            "nome": "INTEL CORE I7-10700KF",
            "marca": "Intel",
            "frequencia": "4",
            "frequencia_max": "5",
            "socket": "LGA1200",
            "tdp": "95",
            "consumo_max": "143",
            "createdAt": "2021-06-08T01:03:11.000Z",
            "updatedAt": "2021-06-08T01:03:11.000Z"
        },
        {
            "id": 2,
            "nome": "INTEL CORE I7-10700KF",
            "marca": "Intel",
            "frequencia": "4",
            "frequencia_max": "5",
            "socket": "LGA1200",
            "tdp": "95",
            "consumo_max": "143",
            "createdAt": "2021-06-08T15:19:11.000Z",
            "updatedAt": "2021-06-08T15:19:11.000Z"
        }
    ],
    CadastroPlacaMae: {
      "nome":"Asus TUF Gaming Z490-Plus",
      "socket":"LGA1200",
      "frequencia_max_ram":4800,
      "max_ram":128,
      "ddr":4
    },
    ListarPlacaMae: [
      {
          "id": 1,
          "nome": "Asus TUF Gaming Z490-Plus",
          "socket": "LGA1200",
          "frequencia_max_ram": "4800",
          "max_ram": 128,
          "ddr": 4,
          "consumo": "35",
          "createdAt": "2021-06-08T01:03:48.000Z",
          "updatedAt": "2021-06-08T01:03:48.000Z"
      }
    ],
    CadastroRam: {
      "nome":"TEAM GROUP T-FORCE RGB 8GB",
      "frequencia":3600,
      "capacidade":8,
      "ddr":4
    },
    ListarRam : [
      {
          "nome": "TEAM GROUP T-FORCE RGB 8GB",
          "frequencia": 5000,
          "capacidade": 8,
          "ddr": 4,
          "consumo": "3"
      },
      {
          "nome": "TEAM GROUP T-FORCE RGB 8GB",
          "frequencia": 3600,
          "capacidade": 8,
          "ddr": 4,
          "consumo": "3"
      }
    ],
    CadastroArmazenamento: {
      "tipo":"SSD",
      "nome":"WD GREEN SN350",
      "capacidade":280
    },
    ListarArmazenamento: [
      {
          "id": 1,
          "tipo": "SSD",
          "nome": "WD GREEN SN350",
          "capacidade": 280,
          "consumo": "12",
          "createdAt": "2021-06-08T01:03:55.000Z",
          "updatedAt": "2021-06-08T01:03:55.000Z"
      },
      {
          "id": 2,
          "tipo": "SSD",
          "nome": "WD GREEN SN350",
          "capacidade": 280,
          "consumo": "12",
          "createdAt": "2021-06-08T15:23:19.000Z",
          "updatedAt": "2021-06-08T15:23:19.000Z"
      }
    ],
    CadastroVga: {
      "nome":"AMD Radeon RX 6800 XT",
      "capacidade":16,
      "tdp":300
    },
    ListarVga: [
      {
          "id": 1,
          "nome": "AMD Radeon RX 6800 XT",
          "capacidade": 16,
          "tdp": "300",
          "consumo_max": "450",
          "createdAt": "2021-06-08T01:04:00.000Z",
          "updatedAt": "2021-06-08T01:04:00.000Z"
      },
      {
        "id": 2,
        "nome": "AMD Radeon RX 6800 XT",
        "capacidade": 16,
        "tdp": "300",
        "consumo_max": "450",
        "createdAt": "2021-06-08T01:04:00.000Z",
        "updatedAt": "2021-06-08T01:04:00.000Z"
    }
    ],
    CadastroFonte: {
      "nome":"fonte b",
      "capacidade":750
    },
    ListarFontes: [
      {
          "id": 1,
          "nome": "fonte b",
          "capacidade": 750,
          "createdAt": "2021-06-08T01:04:06.000Z",
          "updatedAt": "2021-06-08T01:04:06.000Z"
      },
      {
          "id": 2,
          "nome": "fonte b",
          "capacidade": 750,
          "createdAt": "2021-06-13T14:48:33.000Z",
          "updatedAt": "2021-06-13T14:48:33.000Z"
      }
    ],
    IdHardware: {
      "id": 1
    },
    AdicionarProcessadorResponse201: {
      "processador": {
        "id": 1,
        "nome": "INTEL CORE I7-10700KF",
        "marca": "Intel",
        "frequencia": "4",
        "frequencia_max": "5",
        "socket": "LGA1200",
        "tdp": "95",
        "consumo_max": "143",
        "createdAt": "2021-06-08T01:03:11.000Z",
        "updatedAt": "2021-06-08T01:03:11.000Z"
      },
      "computador_agora": {
          "Processador": {
              "id": 1,
              "nome": "INTEL CORE I7-10700KF",
              "marca": "Intel",
              "frequencia": "4",
              "frequencia_max": "5",
              "socket": "LGA1200",
              "tdp": "95",
              "consumo_max": "143",
              "createdAt": "2021-06-08T01:03:11.000Z",
              "updatedAt": "2021-06-08T01:03:11.000Z"
          }
      }
    },
    AdicionarProcessadorResponse422ProcessadorIndisponivel: {
      "status": 422,
      "message": "Processador indisponivel!"
    },
    AdicionarProcessadorResponse422PlacaMaeNaoCompativel: {
      status:422,
      message:"Placa mae nao compativel com este processador!"
    },
    AdicionarPlacaMaeResponse201: {
      "status": 201,
      "placa_mae": {
          "id": 1,
          "nome": "Asus TUF Gaming Z490-Plus",
          "socket": "LGA1200",
          "frequencia_max_ram": 4800,
          "max_ram": 128,
          "ddr": 4,
          "consumo": "35",
          "createdAt": "2021-06-08T01:03:48.000Z",
          "updatedAt": "2021-06-08T01:03:48.000Z"
      },
      "computador_agora": {
          "Processador": {
              "id": 1,
              "nome": "INTEL CORE I7-10700KF",
              "marca": "Intel",
              "frequencia": "4",
              "frequencia_max": "5",
              "socket": "LGA1200",
              "tdp": "95",
              "consumo_max": "143",
              "createdAt": "2021-06-08T01:03:11.000Z",
              "updatedAt": "2021-06-08T01:03:11.000Z"
          },
          "PlacaMae": {
              "id": 1,
              "nome": "Asus TUF Gaming Z490-Plus",
              "socket": "LGA1200",
              "frequencia_max_ram": 4800,
              "max_ram": 128,
              "ddr": 4,
              "consumo": "35",
              "createdAt": "2021-06-08T01:03:48.000Z",
              "updatedAt": "2021-06-08T01:03:48.000Z"
          }
      }
    },
    AdicionarPlacaMaeResponse422PlacaMaeIndisponivel: {
      status:422,
      message:`Placa Mae indisponivel!`
    },
    AdicionarPlacaMaeResponse422FaltaProcessador:{
      status:422,
      message:`Necessario selecionar um processador!`
    },
    AdicionarPlacaMaeResponse422SocketIncompativel: {
      status:422,
      message:"Socket da Placa Mae(LGA1200) incompativel com o socket do Processador(AM4)!"
    },
    AdicionarRamResponse201:{
      "status": 201,
      "message": "Memoria Ram adicionada!",
      "ram": {
          "id": 2,
          "nome": "TEAM GROUP T-FORCE RGB 8GB",
          "frequencia": 3600,
          "capacidade": 8,
          "ddr": 4,
          "consumo": "3",
          "createdAt": "2021-06-08T01:16:19.000Z",
          "updatedAt": "2021-06-08T01:16:19.000Z"
      },
      "computador_agora": {
          "Processador": {
              "id": 1,
              "nome": "INTEL CORE I7-10700KF",
              "marca": "Intel",
              "frequencia": "4",
              "frequencia_max": "5",
              "socket": "LGA1200",
              "tdp": "95",
              "consumo_max": "143",
              "createdAt": "2021-06-08T01:03:11.000Z",
              "updatedAt": "2021-06-08T01:03:11.000Z"
          },
          "PlacaMae": {
              "id": 1,
              "nome": "Asus TUF Gaming Z490-Plus",
              "socket": "LGA1200",
              "frequencia_max_ram": 4800,
              "max_ram": 128,
              "ddr": 4,
              "consumo": "35",
              "createdAt": "2021-06-08T01:03:48.000Z",
              "updatedAt": "2021-06-08T01:03:48.000Z"
          },
          "Ram": {
              "id": 2,
              "nome": "TEAM GROUP T-FORCE RGB 8GB",
              "frequencia": 3600,
              "capacidade": 8,
              "ddr": 4,
              "consumo": "3",
              "createdAt": "2021-06-08T01:16:19.000Z",
              "updatedAt": "2021-06-08T01:16:19.000Z"
          }
      }
    },
    AdicionarRamResponse422MemoriaIndisponivel:{
      status:422,
      message:`Memoria Ram indisponivel.`
    },
    AdicionarRamResponse422FrequenciaIncompativel:{
      status:422,
      message:"Frequencia da Memoria Ram(5000) incompativel com a frequencia suportada pela Placa Mae(4800)!"
    },
    AdicionarRamResponse422CapacidadeIncompativel: {
      status:422,
      message:`Capacidade da Memoria Ram(32) incompativel com a capacidade maxima de ram da Placa Mae(16)!`
    },
    AdicionarRamResponse422FaltaPlacaMae:{
      status:422,
      message:`Necessario selecionar uma Placa Mae!!`
    },
    AdicionarArmazenamento201: {
      "status": 201,
      "message": "Meio de armazenamento adicionado com sucesso!",
      "armazenamento": {
          "id": 1,
          "tipo": "SSD",
          "nome": "WD GREEN SN350",
          "capacidade": 280,
          "consumo": "12",
          "createdAt": "2021-06-08T01:03:55.000Z",
          "updatedAt": "2021-06-08T01:03:55.000Z"
      },
      "computador_agora": {
          "Armazenamento": {
              "id": 1,
              "tipo": "SSD",
              "nome": "WD GREEN SN350",
              "capacidade": 280,
              "consumo": "12",
              "createdAt": "2021-06-08T01:03:55.000Z",
              "updatedAt": "2021-06-08T01:03:55.000Z"
          }
      }
    },
    AdicionarArmazenamento422ArmazenamentoIndisponivel:{
      status:422,
      message:"Meio de Armazenamento indisponivel!"
    },
    AdicionarVga201: {
      "status": 201,
      "message": "Vga adicionada com sucesso!",
      "vga": {
          "id": 1,
          "nome": "AMD Radeon RX 6800 XT",
          "capacidade": 16,
          "tdp": "300",
          "consumo_max": "450",
          "createdAt": "2021-06-08T01:04:00.000Z",
          "updatedAt": "2021-06-08T01:04:00.000Z"
      },
      "computador_agora": {
          "Armazenamento": {
              "id": 1,
              "tipo": "SSD",
              "nome": "WD GREEN SN350",
              "capacidade": 280,
              "consumo": "12",
              "createdAt": "2021-06-08T01:03:55.000Z",
              "updatedAt": "2021-06-08T01:03:55.000Z"
          },
          "Vga": {
              "id": 1,
              "nome": "AMD Radeon RX 6800 XT",
              "capacidade": 16,
              "tdp": "300",
              "consumo_max": "450",
              "createdAt": "2021-06-08T01:04:00.000Z",
              "updatedAt": "2021-06-08T01:04:00.000Z"
          }
      }
    },
    AdicionarVga422VgaIndisponivel: {
      status:422,
      message:"Vga indisponivel!"
    },
    AdicionarFonte201: {
      "status": 201,
      "message": "Fonte adicionada!",
      "fonte": {
          "id": 1,
          "nome": "fonte b",
          "capacidade": 750,
          "createdAt": "2021-06-08T01:04:06.000Z",
          "updatedAt": "2021-06-08T01:04:06.000Z"
      }
    },
    AdicionarFonte422FonteIndisponivel:{
      status:422,
      message: `Fonte nao disponivel!`
    },
    AdicionarFonte422CapacidadeExcedida:{
      status:422,
      message:`O consumo exigido (950) excede a capacidade da fonte(850)!`
    },
    AdicionarComputador201:{
      "status": 201,
      "computador": {
          "id": 6,
          "UsuarioId": 1,
          "ProcessadorId": 1,
          "PlacaMaeId": 1,
          "RamId": 2,
          "ArmazenamentoId": 1,
          "VgaId": 1,
          "FonteId": 1,
          "updatedAt": "2021-06-13T20:51:15.544Z",
          "createdAt": "2021-06-13T20:51:15.544Z"
      },
      "computador_montado": {
          "Processador": {
              "id": 1,
              "nome": "INTEL CORE I7-10700KF",
              "marca": "Intel",
              "frequencia": "4",
              "frequencia_max": "5",
              "socket": "LGA1200",
              "tdp": "95",
              "consumo_max": "143",
              "createdAt": "2021-06-08T01:03:11.000Z",
              "updatedAt": "2021-06-08T01:03:11.000Z"
          },
          "PlacaMae": {
              "id": 1,
              "nome": "Asus TUF Gaming Z490-Plus",
              "socket": "LGA1200",
              "frequencia_max_ram": 4800,
              "max_ram": 128,
              "ddr": 4,
              "consumo": "35",
              "createdAt": "2021-06-08T01:03:48.000Z",
              "updatedAt": "2021-06-08T01:03:48.000Z"
          },
          "Ram": {
              "id": 2,
              "nome": "TEAM GROUP T-FORCE RGB 8GB",
              "frequencia": 3600,
              "capacidade": 8,
              "ddr": 4,
              "consumo": "3",
              "createdAt": "2021-06-08T01:16:19.000Z",
              "updatedAt": "2021-06-08T01:16:19.000Z"
          },
          "Armazenamento": {
              "id": 1,
              "tipo": "SSD",
              "nome": "WD GREEN SN350",
              "capacidade": 280,
              "consumo": "12",
              "createdAt": "2021-06-08T01:03:55.000Z",
              "updatedAt": "2021-06-08T01:03:55.000Z"
          },
          "Vga": {
              "id": 1,
              "nome": "AMD Radeon RX 6800 XT",
              "capacidade": 16,
              "tdp": "300",
              "consumo_max": "450",
              "createdAt": "2021-06-08T01:04:00.000Z",
              "updatedAt": "2021-06-08T01:04:00.000Z"
          },
          "Fonte": {
              "id": 1,
              "nome": "fonte b",
              "capacidade": 750,
              "createdAt": "2021-06-08T01:04:06.000Z",
              "updatedAt": "2021-06-08T01:04:06.000Z"
          }
      }
    },
    AdicionarComputador422ComponentesFaltando: {
      status:422,
      message:"Ha componentes nao adicionados!"
    },
    AdicionarComputadorComIdsDosHardwares: {
      "UsuarioId":1,
      "ProcessadorId":1,
      "PlacaMaeId":1,
      "RamId":1,
      "ArmazenamentoId":1,
      "VgaId":1,
      "FonteId":1
    },
    AdicionarComputadorComIdsDosHardwares201: {
      "id": 1,
      "UsuarioId": 1,
      "ProcessadorId": 1,
      "PlacaMaeId": 1,
      "RamId": 1,
      "ArmazenamentoId": 1,
      "VgaId": 1,
      "FonteId": 1,
      "updatedAt": "2021-06-15T00:15:49.667Z",
      "createdAt": "2021-06-15T00:15:49.667Z"
    },
    AdicionarComputadorComIdsDosHardwares422ProblemaAoAdicionarHardware: {
      "status": 422,
      "message": "Nao foi possivel adicionar hardware ao computador!",
      "error": "Usuario nao cadastrado!"
    },
    AdicionarComputadorComIdsDosHardwares400IdHardwareFaltando: {
      "status": 400,
      "message": "Ha campos faltando na requisicao: UsuarioId"
    }
  }
}
swaggerAutogen(outputFile, endpointsFiles,doc).then(() => {
    require('./app.js');
})